# Code By: Reham Essam ElDin ElTagoury
# Group: 5

# Problem 1
## 1. Your data table rows represent 1000 different clients picked at random and are independent
## 2. Each data sample (i.e. table row) has some attributes with random values (continuous and discrete), namely: 
M = Marital status

ND = No. of dependents

AI = Client’s annual income

R = Risk associated to No-cashback

HA = Has previous approved loan

AA = Amount of previously approved loan

TA = Time until loan is approved

YA = Year of last approved loan


## Import Libararies

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

## 3. The marital status (M) is either Married (1) or Other (0). “Other” may represent singles, widows and divorced. Construct a 1000 samples with probability of being married = 0.6 [Hint: n=1]

In [5]:
# binomial dist
M = np.random.binomial(1,0.6,size=1000)
### Testing ###
M
### Testing ###

array([1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,

## 4. The No. of dependents (ND) like children, spouse, parents, in-laws, etc. whom the client might need to finance yearly over the duration of the loan is modelled by poisson  distribution. Construct a 1000 samples with average ND is 2. [Hint: lambda=2]

In [6]:
ND = np.random.poisson(2,size = 1000)
### Testing ###
ND
### Testing ###

array([3, 1, 4, 0, 2, 3, 3, 2, 4, 3, 3, 0, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1,
       2, 2, 0, 0, 1, 1, 1, 1, 2, 2, 1, 3, 1, 2, 2, 2, 2, 3, 3, 0, 4, 2,
       1, 0, 1, 1, 1, 1, 1, 4, 1, 2, 7, 5, 1, 0, 4, 3, 0, 2, 1, 0, 3, 1,
       2, 2, 0, 1, 1, 1, 5, 4, 0, 2, 1, 2, 3, 3, 2, 2, 0, 4, 0, 4, 2, 1,
       0, 3, 0, 2, 4, 1, 1, 3, 2, 1, 0, 3, 1, 0, 1, 5, 1, 1, 3, 2, 2, 5,
       3, 3, 2, 1, 3, 0, 0, 2, 1, 2, 1, 2, 2, 3, 1, 3, 1, 2, 2, 1, 4, 2,
       2, 3, 2, 1, 4, 0, 2, 4, 3, 3, 0, 0, 1, 5, 3, 3, 3, 0, 2, 0, 2, 2,
       3, 0, 2, 2, 0, 3, 1, 3, 0, 2, 2, 3, 3, 4, 0, 3, 4, 4, 2, 4, 2, 2,
       3, 2, 1, 3, 6, 2, 3, 1, 1, 2, 3, 2, 0, 0, 3, 2, 0, 1, 5, 2, 3, 2,
       1, 0, 3, 2, 3, 3, 2, 1, 4, 3, 1, 1, 2, 1, 1, 2, 3, 0, 3, 3, 1, 1,
       2, 5, 2, 2, 3, 1, 2, 1, 1, 0, 3, 4, 4, 2, 1, 2, 0, 1, 2, 1, 2, 2,
       2, 3, 1, 3, 3, 4, 0, 2, 3, 2, 2, 1, 2, 2, 1, 1, 1, 4, 3, 0, 4, 1,
       1, 2, 2, 0, 3, 1, 5, 3, 1, 3, 1, 1, 3, 2, 3, 3, 0, 4, 3, 6, 1, 0,
       1, 0, 4, 2, 2, 1, 2, 1, 2, 2, 3, 0, 1, 2, 2,

## 5. The client’s annual income in order of 1k (AI) is supposed to be obeying a normal distribution N(80,20). Construct 1000 samples.

In [7]:
AI = np.random.normal(80,20,1000)
### Testing ###
AI
### Testing ###

array([ 98.14701306, 101.80551371, 106.28076652,  43.41325296,
        77.65141157,  65.85075743, 106.20199218,  94.36661175,
        94.65864755,  85.84092635,  73.15876134,  74.6570177 ,
        70.70884786,  63.664413  ,  78.7931125 ,  97.1356004 ,
        89.58454553, 108.6298284 ,  66.62069362,  89.4162074 ,
        78.91519923,  79.10644414,  87.90358603,  61.86044385,
        91.78686105,  92.41744877,  96.44004971,  66.38148437,
        52.32365128, 104.26791387, 103.62130849,  93.69744425,
        80.23951246,  33.29781539,  99.86993832,  85.48685053,
        88.1418984 ,  87.23661644,  85.87596491,  93.24410498,
        70.80251953,  92.10196878,  82.74130066, 101.42287151,
       113.45240455,  82.36287702,  87.30770122,  84.43912048,
        87.63126988, 121.51630328, 158.75833641,  71.48582611,
        76.58977591, 105.53097529,  81.24495867,  93.73540374,
        78.10980049,  66.23512891,  73.56669195,  64.01163133,
        87.3230348 ,  76.58008741,  98.06421011,  77.71

## 6. The risk associated to No-cashback (R), is either high (>0.5) or low (<=0.5) and is given be the following formula: 
R = 12*(ND+1)/AI

Construct 1000 samples.

In [8]:
R = 12*(ND+1)/AI
### Testing ###
R
### Testing ###

array([0.48906226, 0.23574362, 0.56454241, 0.27641329, 0.46361037,
       0.728921  , 0.45196892, 0.38149086, 0.63385651, 0.55917384,
       0.65610734, 0.16073506, 0.50913006, 0.56546504, 0.45689273,
       0.24707728, 0.26790335, 0.33140069, 0.36024843, 0.40261157,
       0.45618588, 0.30338868, 0.40953961, 0.58195509, 0.13073767,
       0.12984561, 0.24885927, 0.3615466 , 0.45868359, 0.23017627,
       0.34741889, 0.38421539, 0.29910451, 1.44153601, 0.24031255,
       0.4211174 , 0.40843232, 0.41267075, 0.41920926, 0.51477785,
       0.67794198, 0.13029037, 0.72515176, 0.35494952, 0.21154245,
       0.14569671, 0.27488984, 0.28422845, 0.27387484, 0.19750436,
       0.15117316, 0.83932722, 0.31335775, 0.34113207, 1.18161178,
       0.76811959, 0.30725978, 0.18117274, 0.81558649, 0.74986372,
       0.13742079, 0.47009609, 0.24473761, 0.15441493, 0.68137678,
       0.33211291, 0.42757275, 0.34335441, 0.33670721, 0.34797315,
       0.3899544 , 0.24491877, 0.75952496, 0.78086702, 0.15906

## 7. The past experience whether or not the client has had a previous approved loan (HA) is either Yes (=1) or No (=0).  Construct a 1000 samples with probability of being cashed a loan = 0.3 [Hint: n=1]

In [9]:
HA = np.random.binomial(1,0.3,size=1000)
### Testing ###
HA
### Testing ###

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,

## 8. The amount of previously approved loan (AA) is supposed to be a function of a normal distribution N(100,10). 

AA = HA * [0.1*AI + R * N(100,10)]

In other words, if he was cashed a previous loan (HA = 1) he got a legal amount of 10% of his annual income in addition to a percentage of 100k with tolerance, conditioned with his risk factor. Construct 1000 samples.


In [10]:
N = np.random.normal(100,10,1000)
AA = HA * [0.1*AI + R * N]
### Testing ###
AA
### Testing ###

array([[  0.        ,  35.61444547,  62.83622023,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
         33.49748098,   0.        ,   0.        ,   0.        ,
          0.        ,  36.79884439,   0.        ,  54.18005514,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  45.69325988,   0.        ,
          0.        ,   0.        ,  34.00238604,   0.        ,
          0.        ,  49.07946366,   0.        ,   0.        ,
          0.        ,   0.        ,  83.26434818,   0.        ,
          0.        ,  21.19443104,  34.42950501,  35.07220552,
         35.27634771,  32.03916086,   0.        ,   0.        ,
          0.        ,   0.        , 110.13768239,  86.46044883,
          0.        ,  25.00355385,   0.        ,   0.        ,
          0.        ,  49.88410462,   0.

## 9. The time until he was granted the approval of his previous loan (TA) is exponentially distributed with scale parameter = 2

TA = HA* Exp(lambda)

Construct 1000 samples.

In [33]:
n = 1000
s = 2
TA = HA*np.random.exponential(s,n)
TA

array([0.00000000e+00, 5.75932391e+00, 8.19362788e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.45348017e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.20590016e+00, 0.00000000e+00, 3.13579896e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.09267078e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 5.54839846e-01, 0.00000000e+00,
       0.00000000e+00, 4.41042194e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.49304143e+00, 0.00000000e+00,
       0.00000000e+00, 2.13878850e+00, 2.43769446e-02, 1.42446633e+00,
       1.12880758e+00, 2.83622176e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.25214067e+00, 1.58182129e+00,
      

## 10. The year of last approved loan (YA) is uniformly distributed between 2000-2020.

YA = HA* {U(2000,2020)}

Construct 1000 samples.

In [34]:
n = 1000
YA = np.random.uniform(2000, 2020, n)
print(YA)

[2015.14653087 2011.56935718 2007.47958978 2011.9097411  2010.89347497
 2017.75347822 2001.21389576 2018.00953605 2017.03726065 2008.18156515
 2002.9252776  2001.46763082 2007.69653626 2002.2679527  2004.45276225
 2007.04838186 2000.18215676 2018.08409105 2013.90700191 2012.34997476
 2004.55014951 2004.41497424 2001.05822367 2001.0510752  2000.1121711
 2006.78599942 2014.16270968 2016.45040638 2001.24513354 2005.23915654
 2002.36007532 2006.37166211 2013.98769546 2018.0268352  2019.26329479
 2014.10237019 2000.55720548 2014.56715296 2007.01380391 2003.3037355
 2013.67604893 2009.44458854 2015.91223511 2011.6500976  2012.32723874
 2000.07776294 2010.78441176 2003.09299057 2008.9169805  2007.21182337
 2004.49522577 2003.95201796 2008.51448133 2001.68316478 2014.98171891
 2001.47549901 2003.9340956  2000.02478534 2004.75648771 2009.17422453
 2005.46122225 2015.64469459 2010.88243457 2008.315657   2019.59347053
 2019.24539902 2000.0092853  2000.09391858 2005.25598055 2017.85526636
 2004.98

### a. Probability to get a loan application by a single client with 2 parent dependents

In [41]:
count=0
for i in range(1000):
    if M[i]==0 and ND[i]==2:
        count+=1
prob=count/1000
prob

0.122

### b. Probability that a loan application will take more than 5 months to get approved

In [36]:
count=0
for i in range(1000):
    if TA[i]>5:
        count+=1
prob=count/1000
prob

0.025

### c. Describe the relationship between the no. of dependents (ND) and the risk factor (R)

In [37]:
np.cov((ND,R))

array([[2.01438939, 0.32952183],
       [0.32952183, 0.08221529]])

In [38]:
np.corrcoef((ND,R))

array([[1.        , 0.80972246],
       [0.80972246, 1.        ]])

### d. Describe the relationship between the annual income (AI) and the risk factor (R)

In [39]:
np.cov((AI,R))

array([[ 4.10641100e+02, -3.03217814e+00],
       [-3.03217814e+00,  8.22152866e-02]])

In [40]:
np.corrcoef((AI,R))

array([[ 1.        , -0.52185184],
       [-0.52185184,  1.        ]])

# Problem 2: Calculating the probability of a given event for a random variable with a binomial distribution

### Step 1: Write the a function that will simulate the same experiment $m$ times of flipping a coin $n$ times (with a probability $p = 1/2$ of getting Head) and calculate the empirical probability of getting $k$ of times of Head to appear among the $n$ coin flips

In [66]:
def calc_emprical(k, n, m):
    x=np.sum(np.sum(np.random.choice([0,1],size=(m,n)),axis=1) == k)
    
    return x/m
##### Testing #####
#calc_emprical(1, 3, 1000)
calc_emprical(10, 20,1000)
##### Testing #####

0.146

### Step 2: Write a function that calculate analytically what is the probability of getting k times Head among n flipping of the coin

In [64]:
def fact(n):
    return 1 if n==1 else n*fact(n-1)
def calc_analyt(k, n):
    ncX=fact(n)/(fact(n-k)*fact(k))
    return ncX * (0.5**k) * (0.5**(n-k))
##### Testing #####
calc_analyt(10, 20)
##### Testing #####

0.17619705200195312

### Step 3: Test your functions with the following values:
- $m=1000$, $n=20$, and $k=10$

In [67]:
print("Analytical solution = ",calc_analyt(10, 20))
print("Empirical solution = ",calc_emprical(10, 20,1000))

Analytical solution =  0.17619705200195312
Empirical solution =  0.164


### Compare  the two values of calculating the probability emprically and analytically. Is this always the same number? If not, what are the possible explanations for these differences?


#### -------------------------------------Write your answer here----------------------------------------------- 



### --------------------------------------------------------------------------------------------

### By comparing the two solutions it turns out that the probabiltity in empirical changes everytime I run that's bec. we use random.choice so it generates diffrenet values every run in order to make them the same solution we need to make the emprical on large number of samples